---
- name: ensure that config dir is created
  file: path='/etc/postgresql/{{ postgres_version }}/{{ postgres_cluster_name }}'
        state=directory mode='u=rwx,g=rx,o=rx' owner=postgres group=postgres

- name: configure postgres
  template:
    src: '{{ item }}'
    dest: '/etc/postgresql/{{ postgres_version }}/{{ postgres_cluster_name }}/{{ item|replace(".j2", "") }}'
    mode: 0640
    owner: postgres
    group: postgres
  with_items:
    - postgresql.conf.j2
    - pg_hba.conf.j2
    - pg_ident.conf.j2
  notify: restart dbserver

- name: ensure there is no recovery.conf file on master
  file: name='{{ postgres_data_directory }}/recovery.conf' state=absent
  when: not postgres_standby|bool
