- name: check if cluster already exists in different dir
  command: 'pg_lsclusters -h {{ postgres_version }} main'
  register: cluster_info
  changed_when: false

- block:
  - name: stop cluster before moving it to new dir
    service: name=postgresql state=stopped
  - name: move cluster to new data dir
    command: 'mv -T {{ cluster_info.stdout.split()[5] }} {{ postgres_data_directory }}'
  when:
    - cluster_info.rc is defined 
    - cluster_info.rc == 0
    - cluster_info.stdout.split()[5] != postgres_data_directory

- name: create cluster
  command: 'pg_createcluster -d {{ postgres_data_directory }} {{ postgres_version }} main'
  register: create_cluster
  changed_when: create_cluster.rc == 0
  failed_when:
    - create_cluster.rc != 0
    - not 'cluster configuration already exists' in create_cluster.stderr 
  when:
    - cluster_info.rc is defined
    - cluster_info.rc != 0
