- name: ensure data directory is present
  file: name='{{ postgres_data_directory }}' state=directory recurse=yes
        owner=postgres group=postgres

- name: check if cluster already exists in different dir
  command: 'pg_lsclusters -h {{ postgres_version }} main'
  register: cluster_info
  changed_when: false
  ignore_errors: yes

- block:
  - name: stop cluster before moving it to new dir
    service: name=postgresql state=stopped
  - name: move cluster to new data dir
    command: 'mv -T {{ cluster_info.stdout.split()[5] }} {{ postgres_data_directory }}'
  when:
    - cluster_info.rc is defined 
    - cluster_info.rc == 0
    - cluster_info.stdout.split()[5] != postgres_data_directory

- name: init cluster
  shell: |
    su -c "/usr/lib/postgresql/{{ postgres_version }}/bin/initdb -D {{ postgres_data_directory }} \
      --locale={{ postgres_locale }} -E {{ postgres_encoding }}" postgres
  register: initdb
  changed_when: initdb.rc == 0
  failed_when:
    - initdb.rc != 0
    - not 'exists but is not empty' in initdb.stderr 
  when: (cluster_info.rc is defined and cluster_info.rc != 0) or not (postgres_data_directory+"/PG_VERSION") is exists

- name: create local wal archive
  file: name='{{ postgres_replication.archive_dest }}' recurse=yes
        state=directory owner=postgres group=postgres
  when:
    - postgres_replication
    - postgres_replication.archive_dest is defined
    - postgres_replication.archive_dest_local is defined
