- block:
  - name: install postgresql server
    apt:
      name:
        - 'postgresql-{{ postgres_version }}'
        - 'postgresql-contrib-{{ postgres_version }}'
        - 'postgresql-client-{{ postgres_version }}'
      default_release: 'l=Debian'
  - name: install postgres exts
    apt: name='postgresql-{{ postgres_version }}-{{ item }}' update_cache=no
    loop: '{{ postgres_exts }}'
  when: postgres_install_os|bool
- block:
  - name: ensure certificates and gnupg is installed
    apt:
      name: [ca-certificates, gnupg, apt-transport-https]
  - name: add PGDG repository key
    apt_key: url='{{ postgres_pgdg.key }}'
  - name: add PGDG apt repository 
    apt_repository: repo='{{ postgres_pgdg.repo }}' 
  - name: install postgresql server
    apt:
      name:
        - 'postgresql-{{ postgres_version }}'
        - 'postgresql-contrib-{{ postgres_version }}'
        - 'postgresql-client-{{ postgres_version }}'
      default_release: '{{ postgres_pgdg.release }}'
  - name: install postgres exts
    apt: name='postgresql-{{ postgres_version }}-{{ item }}' update_cache=no
         default_release='{{ postgres_pgdg.release }}'
    loop: '{{ postgres_exts }}'
  when: not postgres_install_os|bool
- name: install rsync
  apt: name=rsync
