---
- name: install psycopg2 to manage
  apt: name=python-psycopg2
  tags: bootstrap

- name: install locale
  apt: name=locales

- name: generate locale 
  locale_gen: name='{{ postgres_locale }}'

- import_tasks: install.yml
  when: postgres_install|bool
  tags: [postgres_install, install]

- name: ensure data directory is present
  file: name='{{ postgres_data_directory }}' state=directory
        owner=postgres group=postgres

- import_tasks: data_dir.yml
  tags: [postgres_datadir]
  when:
    - postgres_data_dir|bool
    - not postgres_standby|bool

- import_tasks: configure.yml
  when: postgres_configure|bool
  tags: postgres_configure

- import_tasks: standby.yml
  tags: postgres_standby
  when:
    - postgres_replication
    - postgres_standby|bool

- name: ensure postgres is running
  service: name=postgresql state=started

- meta: flush_handlers

- import_tasks: bootstrap_master.yml
  when: not postgres_standby|bool
  tags: postgres_master
