---
- name: install psycopg2 to manage
  apt: name=python-psycopg2
  tags: bootstrap

- name: install locale
  apt: name=locales

- name: generate locale 
  locale_gen: name='{{ postgres_locale }}'

- import_tasks: install.yml
  when: postgres_install
  tags: postgres_install

- import_tasks: configure.yml
  when: postgres_configure
  tags: postgres_configure

- import_tasks: standby.yml
  tags: postgres_standby
  when:
    - postgres_replication
    - postgres_standby|bool

- name: ensure postgres is running
  service: name=postgresql state=started

- meta: flush_handlers

- import_tasks: bootstrap_master.yml
  when: not postgres_standby|bool
  tags: postgres_master
